// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as HistoryList from "./components/History/HistoryList.bs.js";
import * as TotalBalance from "./components/TotalBalance/TotalBalance.bs.js";
import * as ExpenseContext from "./context/ExpenseContext.bs.js";
import * as IncomeExpenseCmp from "./components/IncomeExpenseForm/IncomeExpenseCmp.bs.js";
import * as AddNewTransactionCmp from "./components/AddNewTransaction/AddNewTransactionCmp.bs.js";

import './App.css'
;

function App(Props) {
  return React.createElement(ExpenseContext.make, {
              children: React.createElement("div", {
                    className: "app"
                  }, React.createElement("h1", {
                        className: "heading"
                      }, "Expense Tracker"), React.createElement(TotalBalance.make, {}), React.createElement(IncomeExpenseCmp.make, {}), React.createElement(HistoryList.make, {}), React.createElement(AddNewTransactionCmp.make, {}))
            });
}

var make = App;

export {
  make ,
}
/*  Not a pure module */
