// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as ExpenseContext from "../../context/ExpenseContext.bs.js";

import './AddNewTransactionCmp.css'
;

function AddNewTransactionCmp(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setText = match[1];
  var text = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setPrice = match$1[1];
  var price = match$1[0];
  var match$2 = React.useState(function () {
        return false;
      });
  var setError = match$2[1];
  var error = match$2[0];
  var match$3 = React.useContext(ExpenseContext.context);
  var addTransaction = match$3.addTransaction;
  var onSubmit = function (e) {
    e.preventDefault();
    if (text === "" || price === "") {
      Curry._1(setError, (function (param) {
              return true;
            }));
    } else {
      Curry._1(setError, (function (param) {
              return false;
            }));
      var price$1 = Belt_Int.fromString(price);
      var price$2 = price$1 !== undefined ? price$1 : 0;
      Curry._1(addTransaction, {
            text: text,
            price: price$2 | 0
          });
    }
    Curry._1(setPrice, (function (param) {
            return "";
          }));
    Curry._1(setText, (function (param) {
            return "";
          }));
  };
  return React.createElement("div", {
              className: "new-transaction"
            }, React.createElement("h3", undefined, "Add New Transaction", React.createElement("hr", undefined)), React.createElement("form", {
                  onSubmit: onSubmit
                }, React.createElement("label", undefined, "Text"), React.createElement("input", {
                      placeholder: "Enter text...",
                      type: "text",
                      value: text,
                      onChange: (function (e) {
                          Curry._1(setText, (function (param) {
                                  return e.target.value;
                                }));
                        })
                    }), error && text <= String(0) ? React.createElement("div", {
                        className: "error-label"
                      }, "Enter text") : "", React.createElement("label", undefined, "Amount"), React.createElement("label", undefined, "negative - expense, positive - income"), React.createElement("input", {
                      placeholder: "Enter amount...",
                      type: "number",
                      value: price,
                      onChange: (function (e) {
                          Curry._1(setPrice, e.target.value);
                        })
                    }), error && price <= String(0) ? React.createElement("div", {
                        className: "error-label"
                      }, "Enter amount") : "", React.createElement("button", {
                      type: "submit"
                    }, "Add transaction")));
}

var make = AddNewTransactionCmp;

export {
  make ,
}
/*  Not a pure module */
