// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as GlobalContext from "../../context/GlobalContext.bs.js";

import './IncomeExpenseForm.css'
;

function IncomeExpenseForm(Props) {
  var match = React.useContext(GlobalContext.context);
  var transactions = match.transactions;
  var income = Belt_Array.reduce(transactions, 0, (function (acc, value) {
          if (value.price >= 0) {
            return acc + value.price | 0;
          } else {
            return acc + 0 | 0;
          }
        }));
  var finalIncome = String(income);
  var expense = Belt_Array.reduce(transactions, 0, (function (acc, value) {
          if (value.price < 0) {
            return acc + value.price | 0;
          } else {
            return acc + 0 | 0;
          }
        }));
  var finalExpense = String(expense);
  return React.createElement("div", {
              className: "income-expense-form"
            }, React.createElement("div", {
                  className: "income"
                }, React.createElement("h3", {
                      className: "income-expense-title"
                    }, "INCOME"), React.createElement("p", {
                      className: "income-money"
                    }, finalIncome)), React.createElement("div", {
                  className: "middle-border"
                }), React.createElement("div", {
                  className: "expense"
                }, React.createElement("h3", {
                      className: "income-expense-title"
                    }, "EXPENSE"), React.createElement("p", {
                      className: "expense-money"
                    }, finalExpense)));
}

var make = IncomeExpenseForm;

export {
  make ,
}
/*  Not a pure module */
